---
- name: Converge
  hosts: all
  pre_tasks:
    - name: ensure apache2 is not started
      service: name=apache2 state=stopped enabled=false
  roles:
    - role: ckan-app
      vars:
        catalog_ckan_email_from: no-reply@data.gov
        datagov_in_service: false
