---
- name: get code
  git:
    repo: "{{ item.repo }}"
    dest: "{{ virtualenv }}/src/{{ item.name }}"
    version: "{{ item.branch | default('master') }}"
    force: yes
    umask: "0022"
  with_items: "{{ pkg }}"
  notify: restart apache2

- name: install requirements for pkg
  pip:
    requirements: "{{ virtualenv }}/src/{{ item.name }}/{{ item.requirements }}"
    virtualenv: "{{ virtualenv }}"
    virtualenv_python: "{{ virtualenv }}/bin/python"
    umask: "0022"
  with_items: "{{ pkg }}"
  when: item.requirements is defined
  notify: restart apache2

- name: run setup
  command: chdir={{ virtualenv }}/src/{{ item.name }} {{ virtualenv }}/bin/python setup.py develop
  with_items: "{{ pkg }}"
  tags:
    - skip_ansible_lint
  notify: restart apache2
