---

datagov_service: inventory
inventory_db_name: inventory_db
inventory_python_home: "{{ python_home }}"
app_type: inventory

# project path
project_source_rollback_path: /usr/lib/ckan-rollback
project_source_new_code_path: /usr/lib/ckan-new
current_source_symlink: /usr/lib/ckan
project_index_path: /usr/lib/ckan

