---
catalog_app_type: worker
catalog_pycsw_cron_enable: false

catalog_ckan_app_version: master
app_repo: https://github.com/GSA/catalog.data.gov

ckan_production_ini_template: catalog-next/etc_ckan_production.ini.j2

catalog_ckan_db_host: "{{ catalog_next_postgresql_login_host }}"
catalog_ckan_db_name: "{{ catalog_next_ckan_db_name }}"
catalog_ckan_db_pass: "{{ catalog_next_postgresql_login_password }}"
catalog_ckan_db_user: "{{ catalog_next_postgresql_login_user }}"

catalog_ckan_redis_host: "{{ catalog_next_ckan_redis_host }}"
catalog_ckan_redis_password: "{{ catalog_next_ckan_redis_password }}"

catalog_ckan_plugins_default:
  - envvars
  - image_view
  - text_view
  - recline_view
  - harvest
  - geodatagov
  - datajson
  - datajson_harvest
  - geodatagov_miscs
  - z3950_harvester
  - arcgis_harvester
  - geodatagov_geoportal_harvester
  - waf_harvester_collection
  - geodatagov_csw_harvester
  - geodatagov_doc_harvester
  - geodatagov_waf_harvester
  - spatial_query
  - datagovtheme
