---
# In sandbox, we use python3 on bionic web hosts
# https://github.com/GSA/datagov-infrastructure-modules/issues/32
ansible_python_interpreter: /usr/bin/python3
common_python_version_number: 2.7.16
