---
- hosts: '!jumpbox'
  serial: "{{ datagov_serial | default(1) }}"
  gather_facts: false
  tasks:
    - name: Check if reboot is required
      stat: path=/var/run/reboot-required
      register: reboot_required

    - name: Reboot host
      shell: "sleep 1 && reboot"
      async: 1
      poll: 0
      when: force_reboot is defined or reboot_required.stat.exists
      register: rebooted

    - name: Wait for host to come up
      local_action: wait_for host={{ ansible_ssh_host }} port=22 delay=60 state=started
      when: rebooted is not skipped
