---
- hosts: '!jumpbox'
  serial: "{{ datagov_serial | default(1) }}"
  gather_facts: false
  tasks:
    - name: Check if reboot is required
      stat: path=/var/run/reboot-required
      register: reboot_required

    - name: Reboot host
      reboot: {}
      when: force_reboot is defined or reboot_required.stat.exists
