---
- name: assert fgdc2iso_saxon_license exists
  fail:
    msg: fgdc2iso_saxon_license is required but has not been defined.
  when: fgdc2iso_saxon_license is undefined

  # Nessus 12085
- name: remove default tomcat files
  file: dest=/opt/tomcat/webapps/{{ item }} state=absent
  with_items:
    - docs
    - examples
    - host-manager
    - manager
    - ROOT

- name: install cron
  apt: name=cron state=present

  # TODO use cron module
- name: copy clean-tmp-files cron
  copy: src=etc/cron.d/clean-tmp-files dest=/etc/cron.d/clean-tmp-files mode=0644

- name: Copying nginix configuration
  template:
    src: "fgdc2iso.nginx.conf.j2"
    dest: "/etc/nginx/sites-enabled/fgdc2iso.nginx.conf"
  notify:
    - reload nginx

- name: copy fgdc2iso app
  copy: src=opt/tomcat/webapps/fgdc2iso.war dest=/opt/tomcat/webapps/fgdc2iso.war mode=0644
  notify: restart tomcat

- name: copy saxon-license.lic
  copy:
    content: |
      {{ fgdc2iso_saxon_license }}
    dest: /etc/saxon-license.lic
    mode: "0644"
