---

datagov_service: inventory

datapusher_build_pkg_branch: datagov/inventory-classic

inventory_app_repo_branch: improved-metadata-form
inventory_db_name: inventory_db
inventory_python_home: "{{ python_home }}"
app_type: inventory

# Inventory Datapusher
inventory_datastore_ro_user: datastore_ro
inventory_datastore_user: datastore

# db credentials
inventory_ckan_db_host: "{{ inventory_postgresql_login_host }}"
inventory_db_user: "{{ inventory_postgresql_login_user }}"
inventory_db_pass: "{{ inventory_postgresql_login_password }}"
datastore_db_server: "{{ inventory_postgresql_login_host }}"
inventory_datapusher_db_pass: "{{ inventory_web_datapusher_db_pass }}"
inventory_datastore_pass: "{{ inventory_web_datastore_pass }}"
inventory_datastore_ro_pass: "{{ inventory_web_datastore_ro_pass }}"

# other
inventory_ckan_bucket_name: "{{ inventory_ckan_s3_bucket_name }}"
inventory_ckan_bucket_prefix: "{{ inventory_ckan_s3_bucket_prefix }}"
ckan_site_domain: "{{ inventory_ckan_service_url }}"

# saml2 authentication (temporarily disabled to allow testing
# https://github.com/GSA/datagov-ckan-multi/issues/326 by non-GSA folks)
inventory_ckan_saml2_enabled: false
inventory_ckan_plugins_additional: [s3filestore]
saml2_site_url: https://inventory.sandbox.datagov.us/

# secrets
ckan_instance_secret: "{{ inventory_ckan_instance_secret }}"
ckan_instance_uuid: "{{ inventory_ckan_instance_uuid }}"
who_ini_secret: "{{ inventory_ckan_who_ini_secret }}"
