---

# db credentials
inventory_ckan_db_host: "{{ inventory_postgresql_login_host }}"
inventory_db_user: "{{ inventory_postgresql_login_user }}"
inventory_db_pass: "{{ inventory_postgresql_login_password }}"
datastore_db_server: "{{ inventory_postgresql_login_host }}"
inventory_datapusher_db_pass: "{{ inventory_web_datapusher_db_pass }}"
inventory_datastore_pass: "{{ inventory_web_datastore_pass }}"
inventory_datastore_ro_pass: "{{ inventory_web_datastore_ro_pass }}"

# other
inventory_ckan_bucket_name: "{{ inventory_ckan_s3_bucket_name }}"
inventory_ckan_bucket_prefix: "{{ inventory_ckan_s3_bucket_prefix }}"
ckan_site_domain: "{{ inventory_ckan_service_url }}"

inventory_app_repo_branch: master

# TODO is this for all databases (inventory, datastore, datapusher)? Don't think we need this
# postgresql_enable_extensions:
#   - postgis

# max login
saml2_site_url: unset

# secrets
ckan_instance_secret: "{{ inventory_ckan_instance_secret }}"
ckan_instance_uuid: "{{ inventory_ckan_instance_uuid }}"
who_ini_secret: "{{ inventory_ckan_who_ini_secret }}"
