---
# In sandbox, we use python3 on bionic web hosts
# https://github.com/GSA/datagov-infrastructure-modules/issues/32
ansible_python_interpreter: /usr/bin/python3

ckan_catalog_next: true
ckan_uses_gunicorn: true

catalog_ckan_service_url: https://catalog-next.sandbox.datagov.us
ckan_site_domain: "{{ urls_public.catalog_next }}"
catalog_ckan_app_version: master
app_repo: https://github.com/GSA/catalog.data.gov

# postgresql_login_host: "{{ catalog_next_postgresql_login_host }}"
# postgresql_login_password: "{{ catalog_next_postgresql_login_password }}"
# postgresql_login_user: "{{ catalog_next_postgresql_login_user }}"

catalog_ckan_db_host: "{{ catalog_next_postgresql_login_host }}"
catalog_ckan_db_name: catalog_db_next
catalog_ckan_db_pass: "{{ catalog_next_postgresql_login_password }}"
catalog_ckan_db_user: "{{ catalog_next_postgresql_login_user }}"

catalog_ckan_plugins_default:
  - envvars
  - image_view
  - text_view
  - recline_view
  - harvest
  - geodatagov
  - datajson
  - datajson_harvest
  - geodatagov_miscs
  - z3950_harvester
  - arcgis_harvester
  - geodatagov_geoportal_harvester
  - waf_harvester_collection
  - geodatagov_csw_harvester
  - geodatagov_doc_harvester
  - geodatagov_waf_harvester
  - spatial_query
  - datagovtheme
