---
- name: Deploy Tomcat
  hosts: catalog-fgdc2iso
  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.java
    - role: robertdebock.tomcat
      vars:
        tomcat_version9: "9.0.36"
        tomcat_instances:
          - name: "tomcat"
            version: 9


- name: Deploy nginx
  hosts: catalog-fgdc2iso
  roles:
    - { role: geerlingguy.nginx, tags: [nginx, provision] }


- name: Deploy fgdc2iso
  hosts: catalog-fgdc2iso
  roles:
    - role: software/datagov-deploy-fgdc2iso
