---
- name: Deploy Tomcat
  hosts: fgdc2iso
  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.java
    - role: robertdebock.tomcat
      vars:
        tomcat_version9: "9.0.36"
        tomcat_instances:
          - name: "tomcat"
            version: 9
    - role: software/datagov-deploy-fgdc2iso
