---
- name: Deploy nginx
  hosts: jenkins
  roles:
    - role: nginxinc.nginx
      vars:
        nginx_branch: stable
        nginx_state: latest
      tags: [nginx, provision]

- name: Config nginx
  hosts: jenkins
  roles:
    - role: nginxinc.nginx_config
      vars:
        nginx_config_cleanup_files:
          - /etc/nginx/conf.d/default.conf

        nginx_config_main_template_enable: true
        nginx_config_main_template:
          template_file: nginx.conf.j2
          conf_file_name: nginx.conf
          conf_file_location: /etc/nginx/
          worker_processes: auto
          pid: /var/run/nginx.pid
          error_log:
            location: /var/log/nginx/error.log
            level: notice
          worker_connections: 1024
          http_enable: true
          http_settings:
            default_type: application/octet-stream
            include: /etc/nginx/mime.types
            access_log_format:
              - name: main
                format: |-
                  '$remote_addr - $remote_user [$time_local] "$request" '
                                      '$status $body_bytes_sent "$http_referer" '
                                      '"$http_user_agent" "$http_x_forwarded_for"'
            access_log_location:
              - name: main
                location: /var/log/nginx/access.log
            sendfile: on
            keepalive_timeout: 65
            server_tokens: "off"
      tags: [nginx, provision]


- name: Install jenkins
  hosts: jenkins
  roles:
    - role: nginxinc.nginx
      tags:
        - nginx
    - role: gsa.datagov-deploy-jenkins
      tags:
        - jenkins
  tasks:
    - name: flush handlers
      meta: flush_handlers

    # https://github.com/geerlingguy/ansible-role-jenkins/blob/8540d6c49f16dcb4def1c87e7b13610223a87aa5/tasks/main.yml#L35
    - name: smoke test
      uri:
        url: "https://{{ jenkins_url }}/cli/"
        return_content: true
        timeout: 5
        body_format: raw
        follow_redirects: "no"
        status_code: 200,403
        # TODO enable cert validation. Staging and production hosts have GSA
        # signed certs which should be valid.
        # https://github.com/GSA/datagov-deploy/issues/900
        validate_certs: false
      register: result
      until: (result.status == 403 or result.status == 200) and (result.content.find("Please wait while") == -1)
      retries: 60
      delay: 1
