---
- name: Provision Jumpbox
  hosts: jumpbox
  roles:
    - {role: gsa.datagov-deploy-jumpbox, tags: [jumpbox]}

- name: logrotate configuration
  hosts: jumpbox
  roles:
    - role: nickhammond.logrotate
      logrotate_scripts:
        - name: ansible
          paths:
            - /home/ubuntu/datagov-deploy/ansible/logs/ansible.log
          options:
            - compress
            - copytruncate
            - daily
            - missingok
            - rotate 20
