---
- name: assert saml2_sp_public_certificate is set
  assert:
    that: saml2_sp_public_certificate is defined
    fail_msg: saml2_sp_public_certificate is required

- name: assert saml2_sp_private_key is set
  assert:
    that: saml2_sp_private_key is defined
    fail_msg: saml2_sp_private_key is required

- name: create saml2 directory
  action: file path=/etc/ckan/saml2/ state=directory mode=0755 owner=root group=www-data

- name: create pki directory
  action: file path=/etc/ckan/saml2/pki state=directory mode=0750 owner=root group=www-data

- name: create attributemaps directory
  action: file path=/etc/ckan/saml2/attributemaps state=directory mode=0755 owner=root group=www-data

# TODO remove me after https://github.com/GSA/datagov-deploy/issues/1968
# Cleanup fallout #1968
- name: copy all needed files
  file: dest=/etc/ckan/saml2/{{ item }} state=absent
  with_items:
    - basic.py
    - saml_uri.py
  notify: reload apache2

# TODO configuration files should live in the application repo
- name: copy all needed files
  copy: src=saml2/ dest=/etc/ckan/saml2/attributemaps mode=0644 owner=root group=www-data
  notify: reload apache2

- name: install saml2 host key
  copy: content={{ saml2_sp_private_key }} dest=/etc/ckan/saml2/pki/mykey.pem mode=0640 owner=root group=www-data
  notify: reload apache2

- name: install saml2 host certificate
  copy: content={{ saml2_sp_public_certificate }} dest=/etc/ckan/saml2/pki/mycert.pem mode=0644 owner=root group=www-data
  notify: reload apache2

- name: Downloads idp metadata
  get_url:
    url: "{{ saml2_idp_metadata_url }}"
    dest: /etc/ckan/saml2/idp.xml
    mode: 0644
  notify: reload apache2
