---
- name: restart redis
  service: name=redis-server state=restarted

- name: reload supervisor
  command: supervisorctl reload
  when:
    - (catalog_app_type == "worker") or ckan_uses_gunicorn
    - datagov_in_service | default(true)
  tags:
    - skip_ansible_lint

- name: reload apache2
  service: name=apache2 state=reloaded
  when:
    - catalog_app_type == "web"
    - datagov_in_service | default(true)
