---
- name: restart apache2
  service: name=apache2 state=restarted
  when: datagov_in_service

- name: reload supervisor
  command: supervisorctl reload
  when: datagov_in_service
  tags:
    - skip_ansible_lint
