---
- name: restart apache2
  service: name=apache2 state=restarted
  when: datagov_in_service

- name: reread supervisor
  command: supervisorctl reread
  tags:
    - skip_ansible_lint

- name: restart ckan
  command: supervisorctl restart ckan
  when:
    - datagov_in_service
    - inventory_next
  tags:
    - skip_ansible_lint
