---
- name: restart apache2
  service: name=apache2 state=restarted
  when: datagov_in_service

- name: reload apache2
  service: name=apache2 state=reloaded
  when: datagov_in_service

- name: reload supervisor
  shell: supervisorctl reread && supervisorctl update
  tags:
    - skip_ansible_lint

- name: restart ckan
  command: supervisorctl restart ckan
  when: datagov_in_service
  tags:
    - skip_ansible_lint
