---
- name: restart apache2
  service: name=apache2 state=restarted
  when: datagov_in_service

- name: restart supervisor
  service: name=supervisor state=restarted

- name: restart ckan
  command: supervisorctl restart ckan
  when: datagov_in_service
  tags:
    - skip_ansible_lint
