---
- name: restart apache2
  service: name=apache2 state=restarted
  when: datagov_in_service

- name: restart supervisor
  service: name=supervisor state=restarted

- name: reread supervisor
  command: supervisorctl reread

- name: restart ckan
  command: supervisorctl restart ckan
  when:
    - datagov_in_service
    - inventory-next
  tags:
    - skip_ansible_lint
