---
name: App Restart Template

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      environ:
        required: true
        type: string
      app_url:
        required: false
        type: string
      app_names:
        required: true
        type: string

    secrets:
      CF_SERVICE_USER:
        required: true
      CF_SERVICE_AUTH:
        required: true

jobs:
  attempt1:
    name: restart (${{ inputs.environ }}) attempt 1
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.app_names) }}
    uses: ./.github/workflows/restart-attempt.yml
    secrets: inherit
    with:
      environ: ${{ inputs.environ }}
      app_url: ${{ inputs.app_url }}
      app: ${{ matrix.app }}
      smoketest: ${{ matrix.smoketest }}
      sleep_before: false

  attempt2:
    name: restart (${{ inputs.environ }}) attempt 2
    needs: attempt1
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.app_names) }}
    uses: ./.github/workflows/restart-attempt.yml
    secrets: inherit
    with:
      environ: ${{ inputs.environ }}
      app_url: ${{ inputs.app_url }}
      app: ${{ matrix.app }}
      smoketest: ${{ matrix.smoketest }}
      sleep_before: true

  attempt3:
    name: restart (${{ inputs.environ }}) attempt 3
    needs: attempt2
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.app_names) }}
    uses: ./.github/workflows/restart-attempt.yml
    secrets: inherit
    with:
      environ: ${{ inputs.environ }}
      app_url: ${{ inputs.app_url }}
      app: ${{ matrix.app }}
      smoketest: ${{ matrix.smoketest }}
      sleep_before: true

  report_failures:
    name: report failures
    if: ${{ failure() && github.ref == 'refs/heads/main' }}
    needs: [attempt1, attempt2, attempt3]
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue if it fails 😢
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
          GITHUB_JOB: ${{ toJson(github)['job'] }}
          GITHUB_ATTEMPTS: ${{ github.run_attempt }}
          LAST_COMMIT: ${{ github.sha }}
          LAST_RUN_BY: ${{ github.actor }}
          RUN_ID: ${{ github.run_id }}
          REPO: ${{ github.repository }}
        with:
          filename: datagov/.github/restart_failure.md
          update_existing: true
