---
name: disable egress proxy

on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'App Name'
        required: true
      appSpace:
        description: 'Cloud Foundry Space'
        required: true

jobs:
  disable-egress-development:
    if: github.event.inputs.appSpace == 'development'
    concurrency: development
    name: disable egress catalog (dev)
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: disable egress
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: bin/disable-egress ${{ github.events.inputs.appName }}
          cf_org: gsa-datagov
          cf_space: ${{ github.events.inputs.appSpace }}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
  disable-egress-staging:
    if: github.event.inputs.appSpace == 'staging'
    concurrency: staging
    name: disable egress catalog (staging)
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: disable egress
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: bin/disable-egress ${{ github.events.inputs.appName }}
          cf_org: gsa-datagov
          cf_space: ${{ github.events.inputs.appSpace }}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
  disable-egress-production:
    if: github.event.inputs.appSpace == 'production'
    concurrency: production
    name: disable egress catalog (production)
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: disable egress
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: bin/disable-egress ${{ github.events.inputs.appName }}
          cf_org: gsa-datagov
          cf_space: ${{ github.events.inputs.appSpace }}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
