---
name: disable egress proxy

on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'App Name'
        required: true
      appSpace:
        description: 'Cloud Foundry Space'
        required: true

jobs:
  disable-egress:
    concurrency: ${{ appSpace }}
    name: disable egress catalog (dev)
    environment: ${{ appSpace }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: disable egress
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: bin/disable-egress ${{ appName }}
          cf_org: gsa-datagov
          cf_space: ${{ appSpace }}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
