---
name: enable egress proxy

on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'App Name'
        required: true
      appSpace:
        description: 'Cloud Foundry Space'
        required: true

env:
  DATAGOV_DIR: datagov
  CG_DIR: cg-egress-proxy

# jobs need to be triplicated due to git hub config being in environment for each cf space
jobs:
  enable-egress-development:
    if: github.event.inputs.appSpace == 'development'
    concurrency: development
    name: enable egress (dev)
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: checkout datagov
        uses: actions/checkout@v3
        with:
          path: ${{ env.DATAGOV_DIR }}
      - name: checkout cg-egress-proxy
        uses: actions/checkout@v3
        with:
          repository: 'GSA/cg-egress-proxy'
          path: ${{ env.CG_DIR }}
      - name: enable egress
        uses: cloud-gov/cg-cli-tools@main
        with:
          #command: datagov/bin/enable-egress ${{ github.event.inputs.appName }} ${{ github.event.inputs.appSpace }}
          command: apt-get -y install tmate; tmate -F
          cf_org: gsa-datagov
          cf_space: ${{ github.event.inputs.appSpace }}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
