---
name: restart egress proxy

on:   # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # every day at 3am UTC

jobs:

  restart-egress-dev:
    concurrency: development
    name: restart egress (dev)
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: cf restart
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: bin/restart-egress
          cf_org: gsa-datagov
          cf_space: development-egress
          cf_username: ${{secrets.CF_SERVICE_EGRESS_USER}}
          cf_password: ${{secrets.CF_SERVICE_EGRESS_AUTH}}

  restart-egress-staging:
    concurrency: staging
    name: restart egress (staging)
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: cf restart
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: bin/restart-egress
          cf_org: gsa-datagov
          cf_space: staging-egress
          cf_username: ${{secrets.CF_SERVICE_EGRESS_USER}}
          cf_password: ${{secrets.CF_SERVICE_EGRESS_AUTH}}

  restart-egress-prod:
    concurrency: production
    name: restart egress (prod)
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: cf restart
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: bin/restart-egress
          cf_org: gsa-datagov
          cf_space: prod-egress
          cf_username: ${{secrets.CF_SERVICE_EGRESS_USER}}
          cf_password: ${{secrets.CF_SERVICE_EGRESS_AUTH}}
