name: Static Site Build & Test Template

on:   # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  build:
    name: Build Static Site
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt update
          if [[ -f package.json ]]; then
            sudo apt install -y npm;
            npm install
          fi        
          sudo apt install ruby
          sudo gem install bundler
          bundle  
      - name: Build
        run: |
          if [[ -f gulpfile.js ]]; then
            ./node_modules/.bin/gulp
          fi
          bundle exec jekyll build
      - name: Test Internal Links
        run: bundle exec htmlproofer --check-html --disable-external _site
