name: Static Site Build & Test Template

on: # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  build:
    name: Build Static Site
    runs-on: ubuntu-22.04 # until appArmor Puppeteer issue fixed: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#issues-with-apparmor-on-ubuntu
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true #runs `bundle install`
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install NPM dependencies
        shell: bash
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Woke scan
        uses: get-woke/woke-action@v0
        with:
          # Cause the check to fail on any broke rules
          fail-on-error: false
